-- USE Pizza;
-- GO

SELECT * FROM orders
ORDER BY ORDER_ID;


-- # NUMBER OF RECORDS
SELECT FORMAT(COUNT(row_id), '##,##,#####') AS 'Number Of Observation'
FROM ORDERS;


-- # TOTAL REVENUE(sales)
SELECT FORMAT(SUM(TOTAL_PRICE), 'C') AS 'Total Sales $' 
FROM ORDERS;


-- # AVERAGE SLAES PER ORDER
WITH CTE_TOTAL_PRICE AS
(
	SELECT ORDER_ID, SUM(TOTAL_PRICE) AS 'TOTAL PRICE' 
	FROM orders
	GROUP BY ORDER_ID
)
SELECT FORMAT(AVG([TOTAL PRICE]), 'C')  AS 'Average Sales Per Order' FROM CTE_TOTAL_PRICE;


-- # TOTAL SOLD PIZZA
SELECT SUM(QUANTITY) FROM ORDERS;


-- # TOTAL NUMBER OF ORDERS

SELECT FORMAT(COUNT(DISTINCT ORDER_ID), '##,##,#####') AS 'Total Orders'
FROM ORDERS;


-- # AVERAGE NUMBER OF PIZZAs PER ORDER
WITH CTE_PIZZA_COUNTS AS
(
	SELECT ORDER_ID, SUM(QUANTITY) AS 'PIZZA COUNT' 
	FROM ORDERS
	GROUP BY ORDER_ID
)SELECT AVG([PIZZA COUNT]) as 'Average Pizzas Per Order' FROM CTE_PIZZA_COUNTS;

-- > SALES TREND FOR EACH MONTH
SELECT DATEPART(mm, ORDER_DATE) AS 'Month Number', 
MAX(DATENAME(M, ORDER_DATE)) AS 'Month Name', 
FORMAT(SUM(TOTAL_PRICE), 'C') AS 'Total Sales'
FROM ORDERS
GROUP BY  DATEPART(mm, ORDER_DATE)
ORDER BY DATEPART(mm, ORDER_DATE)

-- > ORDER NUMBERS BY MONTH
SELECT DATEPART(mm, ORDER_DATE) AS 'Month Number', 
MAX(DATENAME(M, ORDER_DATE)) AS 'Month Name', 
FORMAT(COUNT(DISTINCT ORDER_ID), '##,##,#####') AS 'TOTAL Orders'
FROM ORDERS
GROUP BY  DATEPART(mm, ORDER_DATE)
ORDER BY DATEPART(mm, ORDER_DATE)

-- > SALES TREND FOR EACH QUARTER
SELECT DATEPART(mm, ORDER_DATE) AS 'Month Number', 
MAX(DATENAME(M, ORDER_DATE)) AS 'Month Name', 
FORMAT(SUM(TOTAL_PRICE), 'C') AS 'TOTAL PRICE'
FROM ORDERS
GROUP BY  DATEPART(mm, ORDER_DATE)
ORDER BY DATEPART(mm, ORDER_DATE)


-- > THE TOTLA SALES FOR EACH QUARTER
SELECT DATEPART(Q, ORDER_DATE) AS 'Quarter No.', 
 'Q'+ MAX(DATENAME(Q, ORDER_DATE)) AS 'Quarter', 
FORMAT(SUM(TOTAL_PRICE), 'C') AS 'TOTAL PRICE'
FROM ORDERS
GROUP BY  DATEPART(Q, ORDER_DATE)
ORDER BY DATEPART(q, ORDER_DATE)

-- > WE WANT TO KNOW THE PERCENTAGE OF SALES & TOTAL SALES VIA PIZZA CATEGORY ?!!
SELECT PIZZA_CATEGORY, 
FORMAT(SUM(TOTAL_PRICE),'C') AS 'Total Sales', 
FORMAT(SUM(TOTAL_PRICE) / (SELECT SUM(TOTAL_PRICE) FROM ORDERS) * 100, '0.00') + ' %' AS 'PCT Sales'
FROM orders
GROUP BY PIZZA_CATEGORY
ORDER BY SUM(TOTAL_PRICE) DESC;


-- > So, What If We Need To Get The Totla Amount Of Pizza Sold For Each Category !!
SELECT PIZZA_CATEGORY, 
FORMAT(SUM(QUANTITY),'##,##,####') AS 'Totla Quantity'
FROM orders
GROUP BY PIZZA_CATEGORY
ORDER BY SUM(QUANTITY) DESC;


-- > NOW!! WE WANT TO KNOW THE PERCENTAGE OF SALES & TOTAL SALES VIA PIZZA SIZE ?!
SELECT PIZZA_SIZE, 
FORMAT(SUM(TOTAL_PRICE),'C') AS 'Total Sales', 
FORMAT(SUM(TOTAL_PRICE) / (SELECT SUM(TOTAL_PRICE) FROM ORDERS) * 100, '0.00') + ' %' AS 'PCT Sales'
FROM orders
GROUP BY PIZZA_SIZE
ORDER BY SUM(TOTAL_PRICE) DESC;



-- > NOW .. WE WANT TO KNOW THE TOP 5 PIZZA BY SALES
SELECT TOP 5 PIZZA_NAME, FORMAT(SUM(TOTAL_PRICE), 'C') AS "Total Sales"
FROM ORDERS
GROUP BY PIZZA_NAME
ORDER BY SUM(TOTAL_PRICE) DESC


-- > NOW .. WE WANT TO KNOW THE TOP 5 PIZZA BY QUANTITY
SELECT TOP 5 PIZZA_NAME, FORMAT(SUM(QUANTITY), '##,##,####') AS "Total Quantity"
FROM ORDERS
GROUP BY PIZZA_NAME
ORDER BY SUM(QUANTITY) DESC

